/*jshint esversion: 6 */
module.exports.d1 = [
    [false, false, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
    [false, false, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
    [false, false, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
    [true, false, false, false, 
    true, false, false, true, 
    true, false, false, false, 
    true, false, false, true],
    [false, false, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
];
module.exports.d2 = [
    [false, false, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
    [false, false, false, true, 
    false, true, false, false, 
    false, true, false, false, 
    false, false, false, true],
    [false, false, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
    [true, false, false, false, 
    true, false, false, true, 
    true, false, false, false, 
    true, false, false, true],
    [false, false, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
];
module.exports.d3 = [
    [true, true, false, false, 
    false, false, false, false, 
    false, false, false, false, 
    false, false, false, false],
    [false, false, false, true, 
    false, true, false, false, 
    false, true, false, false, 
    false, false, false, true],
    [false, false, false, false, 
    false, false, false, false, 
    false, true, false, false, 
    false, false, false, false],
    [true, true, false, false, 
    true, false, false, true, 
    true, false, false, false, 
    true, false, false, true],
    [false, false, false, false, 
    false, true, false, false, 
    false, false, false, false, 
    false, false, false, false],
];
